//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autocomp.Nmea.Parser.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autocomp.Nmea.Parser.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autonomous.
        /// </summary>
        public static string GeographicalPositionModes_Autonomous {
            get {
                return ResourceManager.GetString("GeographicalPositionModes_Autonomous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not valid.
        /// </summary>
        public static string GeographicalPositionModes_DataNotValid {
            get {
                return ResourceManager.GetString("GeographicalPositionModes_DataNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential.
        /// </summary>
        public static string GeographicalPositionModes_Differential {
            get {
                return ResourceManager.GetString("GeographicalPositionModes_Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated.
        /// </summary>
        public static string GeographicalPositionModes_Estimated {
            get {
                return ResourceManager.GetString("GeographicalPositionModes_Estimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual input.
        /// </summary>
        public static string GeographicalPositionModes_ManualInput {
            get {
                return ResourceManager.GetString("GeographicalPositionModes_ManualInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulator.
        /// </summary>
        public static string GeographicalPositionModes_Simulator {
            get {
                return ResourceManager.GetString("GeographicalPositionModes_Simulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header is too short..
        /// </summary>
        public static string HeaderIsTooShort {
            get {
                return ResourceManager.GetString("HeaderIsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrectly formatted decimal value..
        /// </summary>
        public static string IncorrectlyFormattedDecimalValue {
            get {
                return ResourceManager.GetString("IncorrectlyFormattedDecimalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CRC..
        /// </summary>
        public static string InvalidCRC {
            get {
                return ResourceManager.GetString("InvalidCRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CRC size..
        /// </summary>
        public static string InvalidCRSSize {
            get {
                return ResourceManager.GetString("InvalidCRSSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data valid.
        /// </summary>
        public static string IsDataValid {
            get {
                return ResourceManager.GetString("IsDataValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude type.
        /// </summary>
        public static string LatitudeType {
            get {
                return ResourceManager.GetString("LatitudeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude type.
        /// </summary>
        public static string LongitudeType {
            get {
                return ResourceManager.GetString("LongitudeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message is empty..
        /// </summary>
        public static string MessageIsEmpty {
            get {
                return ResourceManager.GetString("MessageIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message should be prefixed with {0}..
        /// </summary>
        public static string MessageShouldBePrefixedWith {
            get {
                return ResourceManager.GetString("MessageShouldBePrefixedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message should be suffixed with {0}..
        /// </summary>
        public static string MessageShouldBeSuffixedWith {
            get {
                return ResourceManager.GetString("MessageShouldBeSuffixedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message type {0} is not supported..
        /// </summary>
        public static string MessageTypeNotSupported {
            get {
                return ResourceManager.GetString("MessageTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relative.
        /// </summary>
        public static string NMEAReferenceTypes_Relative {
            get {
                return ResourceManager.GetString("NMEAReferenceTypes_Relative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theoretical.
        /// </summary>
        public static string NMEAReferenceTypes_Theoretical {
            get {
                return ResourceManager.GetString("NMEAReferenceTypes_Theoretical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global positioning system (GPS).
        /// </summary>
        public static string NMEATalkerDevices_GlobalPositioningSystem {
            get {
                return ResourceManager.GetString("NMEATalkerDevices_GlobalPositioningSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather instruments.
        /// </summary>
        public static string NMEATalkerDevices_WeatherInstruments {
            get {
                return ResourceManager.GetString("NMEATalkerDevices_WeatherInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference type.
        /// </summary>
        public static string ReferenceType {
            get {
                return ResourceManager.GetString("ReferenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talker device.
        /// </summary>
        public static string TalkerDevice {
            get {
                return ResourceManager.GetString("TalkerDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature units.
        /// </summary>
        public static string TemperatureUnits {
            get {
                return ResourceManager.GetString("TemperatureUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC time of position.
        /// </summary>
        public static string UTCOfPosition {
            get {
                return ResourceManager.GetString("UTCOfPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind angle [°].
        /// </summary>
        public static string WindAngle {
            get {
                return ResourceManager.GetString("WindAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed.
        /// </summary>
        public static string WindSpeed {
            get {
                return ResourceManager.GetString("WindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind speed unit.
        /// </summary>
        public static string WindSpeedUnit {
            get {
                return ResourceManager.GetString("WindSpeedUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Km/h.
        /// </summary>
        public static string WindSpeedUnits_KMPerHour {
            get {
                return ResourceManager.GetString("WindSpeedUnits_KMPerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knots.
        /// </summary>
        public static string WindSpeedUnits_Knots {
            get {
                return ResourceManager.GetString("WindSpeedUnits_Knots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/s.
        /// </summary>
        public static string WindSpeedUnits_MetersPerSecond {
            get {
                return ResourceManager.GetString("WindSpeedUnits_MetersPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        public static string WorldDirections_East {
            get {
                return ResourceManager.GetString("WorldDirections_East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        public static string WorldDirections_North {
            get {
                return ResourceManager.GetString("WorldDirections_North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        public static string WorldDirections_South {
            get {
                return ResourceManager.GetString("WorldDirections_South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        public static string WorldDirections_West {
            get {
                return ResourceManager.GetString("WorldDirections_West", resourceCulture);
            }
        }
    }
}
